- hosts: terraform-ansible
  tasks:
    - name: Instalando o python3, virtualenv
      apt:
        pkg:
          - python3
          - virtualenv
        update_cache: yes # Atualização dos repositórios
      become: yes #rodar como "sudo"
    - name: Instalando dependencias com pip (Django e Django Rest)
      pip:
        virtualenv: /home/ubuntu/tcc/venv
        name:
          - django
          - djangorestframework
    - name: Verificando se o projeto ja existe
      # obter estado se o arquivo já existe
      stat:
        path: /home/ubuntu/tcc/setup/settings.py
      # guarda a informação numa variável
      register: projeto
    - name: Iniciando o projeto
      shell: ". /home/ubuntu/tcc/venv/bin/activate; django-admin startproject setup /home/ubuntu/tcc/"
      when: not projeto.stat.exists
    - name: Alterando o hosts do settings
      lineinfile:
        path: /home/ubuntu/tcc/setup/settings.py
        regexp: "ALLOWED_HOSTS"
        line: 'ALLOWED_HOSTS = ["*"]'
        backrefs: yes # se não achar o arquivo não faça nada
